### ISSUE TITLE
Update ffi - Security Risk 

### ISSUE THREAD

**Issue by iamciera** [cabinetofcuriosity/cabinetofcuriosity_site#12]
As detailed by Github:

> We found a potential security vulnerability in a repository for which you have been granted security alert access.
> 
> @cabinetofcuriosity	cabinetofcuriosity/cabinetofcuriosity_site
> Known moderate severity security vulnerability detected in ffi < 1.9.24 defined in Gemfile.lock.
> Gemfile.lock update suggested: ffi ~> 1.9.24.

**Comment by DarkoArnautov** [comment]
Fixed in commit 94f4217
