### ISSUE TITLE
Too much blank space for content display on main page, change back to left align.

### ISSUE THREAD

**Issue by iamciera** [cabinetofcuriosity/cabinetofcuriosity_site#15]
Maybe from the last commit [d003265](https://github.com/cabinetofcuriosity/cabinetofcuriosity_site/commit/d003265cdd0513edebc5785b6d25a547bd449ded)

See screenshot below:
![screen shot 2019-01-23 at 1 45 21 pm](https://user-images.githubusercontent.com/1732390/51639232-3bd37980-1f15-11e9-9ab6-e95bddbeaf7f.png)

**Comment by iamciera** [comment]
I know this is only for really wide displays, but it looks kinda weird. Can you change it back to left align until we figure something else out?

**Comment by DarkoArnautov** [comment]
Yes, have backed
