### ISSUE TITLE
Incorporate Tags and Tag Navigation in Side bar

### ISSUE THREAD

**Issue by iamciera** [cabinetofcuriosity/cabinetofcuriosity_site#17]
HOLD OFF ON THIS ISSUE FOR A FEW WEEKS

1. I would like to add tags to the posts that can be defined by post front matter. 
2. In addition, I would like the side bar to navigate to the posts defined by the tags. Bottom  is a quick sketch of the side bar. There will be three tags to start "Visits", "Tutorials", and "Interviews"
3. The side bar will have an  "About" link which is at the top and link to the old about page.

![20190130_153424](https://user-images.githubusercontent.com/1732390/52020556-8ff6d480-24a6-11e9-8961-534f93993f41.jpg)

**Comment by DarkoArnautov** [comment]
Added

**Comment by iamciera** [comment]
I can't seem to get the sidebar navigation to work on on a desktop computer, but it works on my phone.

**Comment by DarkoArnautov** [comment]
http://prntscr.com/mfu6pf

**Comment by DarkoArnautov** [comment]
I can see on my side chrome, firefox, IE

**Comment by iamciera** [comment]
I see. It only happens when I am in the "About" Section. http://curiositydata.org/about/

**Comment by DarkoArnautov** [comment]
About page is not post list page.
In order to working tag filter, we need to redirect to the landing page and run filter function on there.
So, we have to make "All posts" menu in nav, after click that, and then we can run filter function.
Please let me know your suggestion.

**Comment by DarkoArnautov** [comment]
Please check currently solution, and let me know

**Comment by iamciera** [comment]
Thanks! This works.

**Comment by iamciera** [comment]
Thanks!
