### ISSUE TITLE
Put source link at the bottom of the header image

### ISSUE THREAD

**Issue by iamciera** [cabinetofcuriosity/cabinetofcuriosity_site#18]
Can you add image legend to the header image?  Also have it right aligned 
![screen shot 2019-01-30 at 3 57 37 pm](https://user-images.githubusercontent.com/1732390/52020998-342d4b00-24a8-11e9-8849-9db8ee1b4c1b.png).  

Maybe the legend and where it links (original source) can be defined in the front matter?

**Comment by DarkoArnautov** [comment]
Added legend at the bottom-right of header image
