### ISSUE TITLE
Place Author info and image into posts

### ISSUE THREAD

**Issue by iamciera** [cabinetofcuriosity/cabinetofcuriosity_site#19]
I would like to add author information into the YAML front matter of the posts so that their illustrations / avatars appear like below along with their name below. The file for the avatars will be placed into assets/img/avatars.

<img width="846" alt="author" src="https://user-images.githubusercontent.com/1732390/52080405-8758d980-254c-11e9-9b93-67927fcfbb7e.png">

**Comment by DarkoArnautov** [comment]
Added author avatar
