### ISSUE TITLE
Make text smaller (at least with the code)

### ISSUE THREAD

**Issue by iamciera** [cabinetofcuriosity/cabinetofcuriosity_site#2]
I think that the text is way too big. Especially in the code chunks. The wrapping is fine, but would be more readible is the code didn't wrap. Should be pretty straight forward to figure it out how to set global text options in the [`main.css`](https://github.com/cabinetofcuriosity/cabinetofcuriosity_site/blob/master/assets/css/main.css) file.

**Comment by DarkoArnautov** [comment]
Fixed in commit a1655f4.
